//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductDataAccessLayer_Lib
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [Required]
        public int ProductID { get; set; }
        [Required]
        public string Category_ID { get; set; }
        [Required]
        public string Product_Name { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public Nullable<int> Price { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
