//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFWebAppClient.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/EntityLayer")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeptidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Deptid {
            get {
                return this.DeptidField;
            }
            set {
                if ((this.DeptidField.Equals(value) != true)) {
                    this.DeptidField = value;
                    this.RaisePropertyChanged("Deptid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ecode {
            get {
                return this.EcodeField;
            }
            set {
                if ((this.EcodeField.Equals(value) != true)) {
                    this.EcodeField = value;
                    this.RaisePropertyChanged("Ecode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ename {
            get {
                return this.EnameField;
            }
            set {
                if ((object.ReferenceEquals(this.EnameField, value) != true)) {
                    this.EnameField = value;
                    this.RaisePropertyChanged("Ename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IEmpService")]
    public interface IEmpService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpService/GetAllEmps", ReplyAction="http://tempuri.org/IEmpService/GetAllEmpsResponse")]
        WCFWebAppClient.ServiceReference2.Employee[] GetAllEmps();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpService/GetAllEmps", ReplyAction="http://tempuri.org/IEmpService/GetAllEmpsResponse")]
        System.Threading.Tasks.Task<WCFWebAppClient.ServiceReference2.Employee[]> GetAllEmpsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpService/AddEmployee", ReplyAction="http://tempuri.org/IEmpService/AddEmployeeResponse")]
        void AddEmployee(WCFWebAppClient.ServiceReference2.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpService/AddEmployee", ReplyAction="http://tempuri.org/IEmpService/AddEmployeeResponse")]
        System.Threading.Tasks.Task AddEmployeeAsync(WCFWebAppClient.ServiceReference2.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpService/DeleteEmployee", ReplyAction="http://tempuri.org/IEmpService/DeleteEmployeeResponse")]
        void DeleteEmployee(int ecode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpService/DeleteEmployee", ReplyAction="http://tempuri.org/IEmpService/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task DeleteEmployeeAsync(int ecode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpService/UpdateEmpbyEcode", ReplyAction="http://tempuri.org/IEmpService/UpdateEmpbyEcodeResponse")]
        void UpdateEmpbyEcode(int ecode, int Salary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpService/UpdateEmpbyEcode", ReplyAction="http://tempuri.org/IEmpService/UpdateEmpbyEcodeResponse")]
        System.Threading.Tasks.Task UpdateEmpbyEcodeAsync(int ecode, int Salary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpService/GetEmpbyEcode", ReplyAction="http://tempuri.org/IEmpService/GetEmpbyEcodeResponse")]
        WCFWebAppClient.ServiceReference2.Employee GetEmpbyEcode(int ecode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpService/GetEmpbyEcode", ReplyAction="http://tempuri.org/IEmpService/GetEmpbyEcodeResponse")]
        System.Threading.Tasks.Task<WCFWebAppClient.ServiceReference2.Employee> GetEmpbyEcodeAsync(int ecode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpServiceChannel : WCFWebAppClient.ServiceReference2.IEmpService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpServiceClient : System.ServiceModel.ClientBase<WCFWebAppClient.ServiceReference2.IEmpService>, WCFWebAppClient.ServiceReference2.IEmpService {
        
        public EmpServiceClient() {
        }
        
        public EmpServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFWebAppClient.ServiceReference2.Employee[] GetAllEmps() {
            return base.Channel.GetAllEmps();
        }
        
        public System.Threading.Tasks.Task<WCFWebAppClient.ServiceReference2.Employee[]> GetAllEmpsAsync() {
            return base.Channel.GetAllEmpsAsync();
        }
        
        public void AddEmployee(WCFWebAppClient.ServiceReference2.Employee emp) {
            base.Channel.AddEmployee(emp);
        }
        
        public System.Threading.Tasks.Task AddEmployeeAsync(WCFWebAppClient.ServiceReference2.Employee emp) {
            return base.Channel.AddEmployeeAsync(emp);
        }
        
        public void DeleteEmployee(int ecode) {
            base.Channel.DeleteEmployee(ecode);
        }
        
        public System.Threading.Tasks.Task DeleteEmployeeAsync(int ecode) {
            return base.Channel.DeleteEmployeeAsync(ecode);
        }
        
        public void UpdateEmpbyEcode(int ecode, int Salary) {
            base.Channel.UpdateEmpbyEcode(ecode, Salary);
        }
        
        public System.Threading.Tasks.Task UpdateEmpbyEcodeAsync(int ecode, int Salary) {
            return base.Channel.UpdateEmpbyEcodeAsync(ecode, Salary);
        }
        
        public WCFWebAppClient.ServiceReference2.Employee GetEmpbyEcode(int ecode) {
            return base.Channel.GetEmpbyEcode(ecode);
        }
        
        public System.Threading.Tasks.Task<WCFWebAppClient.ServiceReference2.Employee> GetEmpbyEcodeAsync(int ecode) {
            return base.Channel.GetEmpbyEcodeAsync(ecode);
        }
    }
}
